/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiButton: typeof import('./src/components/common/extensions/Commands/AiButton.vue')['default']
    AttachFile: typeof import('./src/components/common/extensions/file/attachFile.vue')['default']
    Bookmark: typeof import('./src/components/common/extensions/bookmark/bookmark.vue')['default']
    Button: typeof import('./src/components/common/extensions/button/button.vue')['default']
    CardIcon: typeof import('./src/components/common/EditorIconCover/CardIcon.vue')['default']
    CodeBlockComponent: typeof import('./src/components/common/extensions/code-block/CodeBlockComponent.vue')['default']
    ColorSelectorDialog: typeof import('./src/components/common/ColorSelectorDialog.vue')['default']
    Column: typeof import('./src/components/common/extensions/column/column.vue')['default']
    Columns: typeof import('./src/components/common/extensions/columns/columns.vue')['default']
    Command: typeof import('./src/components/common/extensions/Commands/Command.vue')['default']
    CommandsList: typeof import('./src/components/common/extensions/Commands/CommandsList.vue')['default']
    CoverDialog: typeof import('./src/components/common/EditorIconCover/CoverDialog.vue')['default']
    Editor: typeof import('./src/components/common/Editor.vue')['default']
    EditorIconCover: typeof import('./src/components/common/EditorIconCover/index.vue')['default']
    EditorMenu: typeof import('./src/components/common/EditorMenu.vue')['default']
    EditorMenuItem: typeof import('./src/components/common/EditorMenuItem.vue')['default']
    EditorMenuUploadItem: typeof import('./src/components/common/EditorMenuUploadItem.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EmbedVideo: typeof import('./src/components/common/extensions/embedVideo/embedVideo.vue')['default']
    FileDownload: typeof import('./src/components/common/viewer/FileDownload.vue')['default']
    HeadingNodeView: typeof import('./src/components/common/extensions/nodeView/HeadingNodeView.vue')['default']
    HorizontalRuleNodeView: typeof import('./src/components/common/extensions/nodeView/HorizontalRuleNodeView.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    IconDialog: typeof import('./src/components/common/EditorIconCover/IconDialog.vue')['default']
    Image: typeof import('./src/components/common/extensions/image/image.vue')['default']
    ImageViewer: typeof import('./src/components/common/viewer/ImageViewer.vue')['default']
    LinkDialog: typeof import('./src/components/common/LinkDialog.vue')['default']
    ListItemNodeView: typeof import('./src/components/common/extensions/nodeView/ListItemNodeView.vue')['default']
    MentionItem: typeof import('./src/components/common/extensions/mentions/MentionItem.vue')['default']
    MentionList: typeof import('./src/components/common/extensions/mentions/MentionList.vue')['default']
    MoveDialog: typeof import('./src/components/common/MoveDialog.vue')['default']
    OfficeViewer: typeof import('./src/components/common/viewer/OfficeViewer.vue')['default']
    ParagraphNodeView: typeof import('./src/components/common/extensions/nodeView/ParagraphNodeView.vue')['default']
    PopoverItemButton: typeof import('./src/components/common/PopoverItemButton.vue')['default']
    ProgressItem: typeof import('./src/components/common/extensions/extension-process/progressItem.vue')['default']
    QtimeWallpaper: typeof import('./src/components/common/EditorIconCover/QtimeWallpaper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Star: typeof import('./src/components/common/extensions/extension-star/star.vue')['default']
    TaskItemNodeView: typeof import('./src/components/common/extensions/nodeView/TaskItemNodeView.vue')['default']
    Tips: typeof import('./src/components/common/extensions/tips/tips.vue')['default']
    Unsplash: typeof import('./src/components/common/EditorIconCover/Unsplash.vue')['default']
    Upload: typeof import('./src/components/common/extensions/Commands/Upload.vue')['default']
    UploadButton: typeof import('./src/components/common/UploadButton.vue')['default']
    Webview: typeof import('./src/components/common/Webview.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
