services:
  mysql:
    image: 'mysql:latest'
    container_name: spring-boot-template-mysql
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
      - 'TZ=Asia/Shanghai'
      - 'MYSQL_CHARACTER_SET_SERVER=utf8mb4'
      - 'MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql # 使用命名卷挂载 MySQL 数据目录
    restart: unless-stopped
    networks:
      - web

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: unless-stopped
    networks:
      - web

  spring-boot-template:
    image: demo-app:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
    networks:
      - web

  vue3-template:
    image: vue3-template:latest
    # ports:
    #   - "5173:80"
    restart: unless-stopped
    depends_on:
      - spring-boot-template
    networks:
      - web
volumes:
  mysql_data: {} # 声明命名卷

networks:
  web:
    driver: bridge
