name: Docker Build and Deploy

on:
  push:
    branches:
      - main # 可根据需要修改触发分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 检出仓库代码

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2 # 配置Docker构建环境

      - name: Build Docker image
        env:
          VITE_PIC_GO_KEY: ${{ secrets.VITE_PIC_GO_KEY }} # 从GitHub Secrets获取密钥
          VITE_AMAP_WEB_KEY: ${{ secrets.VITE_AMAP_WEB_KEY }}
          # 构建镜像并保存为 tar 文件
        run: |
          docker build --build-arg VITE_PIC_GO_KEY=$VITE_PIC_GO_KEY --build-arg VITE_AMAP_WEB_KEY=$VITE_AMAP_WEB_KEY -t vue3-template:latest -f docker/Dockerfile .  # 带参数构建Docker镜像
          docker save -o vue3-template.tar vue3-template:latest  # 将镜像导出为tar文件

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Transfer via SCP
        run: |
          scp vue3-template.tar root@47.102.193.24:/home/docker-images/
          scp docker/vue-template.conf root@47.102.193.24:/etc/nginx/sites-available/
          scp docker/docker-compose.yml root@47.102.193.24:/home/projects/vue-template/

      - name: Deploy on Server
        run: |
          ssh root@47.102.193.24 << EOF
            cd /home/docker-images
            docker load -i vue3-template.tar
            cd /home/projects/vue-template/
            docker compose down && docker compose up -d
            docker image prune -f  # 清理无用镜像
            rm -f vue3-template.tar  # 新增清理tar文件
          EOF
